name: Merging Rules
on:
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master]
jobs:
   e2e-tests:
      name: E2E Tests
      uses: ./.github/workflows/e2e-tests.yml
