name: E2E Tests
on:
   # Run on any commit to the #master branch
   push:
      branches: [master]
jobs:
   e2e-tests:
      name: E2E Tests
      uses: ./.github/workflows/e2e-tests.yml
   update-dependant-repos:
      name: Update Dependant Repos
      runs-on: ubuntu-latest
      needs: e2e-tests
      strategy:
         matrix:
            service:
               - appbuilder
               - custom_reports
               - definition_manager
               - file_processor
               - process_manager
               - user_manager
            branch: [develop]
            # Should we update master branches too?
      steps:
         - name: Checkout ${{ matrix.service }}
           uses: actions/checkout@v3
           with:
              path: ${{ matrix.service }}
              repository: digi-serve/ab_service_${{ matrix.service }}
              ref: ${{ matrix.branch }}
              fetch-depth: 0
              token: ${{ secrets.DS_REPO_PAT }}
              submodules: recursive
         - name: Checkout ${{ matrix.service }} > AppBuilder
           run: git checkout master
           working-directory: ${{ matrix.service }}/AppBuilder
         - uses: EndBug/add-and-commit@v9
           with:
              message: "Update AppBuilder sub-repo (from GitHub Actions)"
              cwd: ${{ matrix.service }}
